hospital/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('signup/pacient/', views.PacientSignUpView.as_view(), name='pacient_signup'),
    path('signup/doctor/', views.DoctorSignUpView.as_view(), name='doctor_signup'),
    path('login/', views.login, name='login'),
]

hospital/hospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hospitalapp.urls')),
    path('accounts/', include('accounts.urls')),

]

hospital/hospitalapp/urls.py
from django.urls import path, include 
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('search_result/', views.search_result, name='search_result'),
    path('patients/', views.patients, name='patients'),
    path('doctors/', views.doctors, name='doctors'),
    path('patient/<int:patient_id>/', views.patient_details, name='patient_details'),
    path('examinations/', views.examinations, name='examinations'),
    path('hospitalizations/', views.hospitalizations, name='hospitalizations'),
    path('dosages/', views.dosages, name='dosages'),
    path('hospitalizations/add/', views.add_hospitalization, name='add_hospitalization'),
    path('hospitalizations/<int:hospitalization_id>/edit/', views.edit_hospitalization, name='edit_hospitalization'),
    path('hospitalizations/<int:hospitalization_id>/delete/', views.delete_hospitalization, name='delete_hospitalization'),
    path('examinations/add/', views.add_examination, name='add_examination'),
    path('examinations/<int:examination_id>/edit/', views.edit_examination, name='edit_examination'),
    path('examinations/<int:examination_id>/delete/', views.delete_examination, name='delete_examination'),
    path('dosages/add/', views.add_dosage, name='add_dosage'),
    path('dosages/<int:dosage_id>/delete/', views.delete_dosage, name='delete_dosage'),
    path('dosages/medications/', views.medications, name='medications'),

]

hospital/hospitalapp/models.py
from django.db import models
from datetime import datetime
from hospital.constants import APPLICATION_METHOD_CHOICES, APPLICATION_METHOD_ORALLY


class Department(models.Model):
    icpe = models.CharField(primary_key=True, max_length=8)
    title = models.CharField(null=False, max_length=100)

    def __str__(self):
        return self.title + '(%s)' % self.icpe


class Hospitalization(models.Model):
    purpose = models.CharField(blank=True, null=True, max_length=400)
    date = models.DateField(blank=False, null=False)
    pacient = models.ForeignKey('accounts.Pacient', on_delete=models.CASCADE)
    doctor = models.ForeignKey('accounts.Doctor', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']


class Examination(models.Model):
    date = models.DateField(blank=False, null=False)
    result = models.CharField(blank=True, null=True, max_length=400)
    pacient = models.ForeignKey('accounts.Pacient', on_delete=models.CASCADE)
    doctor = models.ForeignKey('accounts.Doctor', on_delete=models.CASCADE)
    department = models.ForeignKey('Department', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']


class Medicine(models.Model):
    title = models.CharField(unique=True, null=False,
                             blank=False, max_length=100)
    active_substance = models.CharField(null=True, blank=True, max_length=100)
    medicine_strenght = models.SmallIntegerField(
        verbose_name='Strength(mg)', null=True, blank=True)
    contraindications = models.CharField(null=True, blank=True, max_length=100)

    def __str__(self):
        return self.title


class Dose(models.Model):
    date = models.DateField(default=datetime.now, blank=True, null=True)
    medicine = models.ForeignKey('Medicine', on_delete=models.CASCADE)
    pacient = models.ForeignKey('accounts.Pacient', on_delete=models.CASCADE)
    application_method = models.SmallIntegerField(
        choices=APPLICATION_METHOD_CHOICES, default=APPLICATION_METHOD_ORALLY, null=False, blank=False)

    class Meta:
        ordering = ['-date']

hospital/hospitalapp/forms.py
from secrets import choice
from django import forms
import datetime

from .models import Department, Examination, Hospitalization, Dose, Medicine
from accounts.models import Pacient
from hospital.constants import APPLICATION_METHOD_CHOICES


class AddExaminationForm(forms.ModelForm):

    class Meta:
        model = Examination
        fields = ('result', 'date', 'patient', 'department')

    date = forms.DateField(required=True, initial=datetime.date.today, input_formats=[
                           '%d-%m-%Y', '%Y-%m-%d', '%d.%m.%Y', '%Y.%m.%d'], )
    result = forms.CharField(required=True, widget=forms.Textarea(
        attrs={'name': 'body', 'rows': '3', 'cols': '50'}))

    patient = forms.ModelChoiceField(
        required=True, queryset=Pacient.objects.all(),
    )
    department = forms.ModelChoiceField(
        queryset=Department.objects.all(),
    )


class EditExaminationForm(forms.ModelForm):

    class Meta:
        model = Examination
        fields = ('result', 'date', 'department')

    date = forms.DateField(required=True, initial=datetime.date.today, input_formats=[
        '%d-%m-%Y', '%Y-%m-%d', '%d.%m.%Y', '%Y.%m.%d'], )
    result = forms.CharField(required=True, widget=forms.Textarea(
        attrs={'name': 'body', 'rows': '3', 'cols': '50'}))

    department = forms.ModelChoiceField(
        queryset=Department.objects.all(),
    )


class AddHospitalizationForm(forms.ModelForm):

    class Meta:
        model = Hospitalization
        fields = ('purpose', 'date', 'patient')

    date = forms.DateField(required=True, initial=datetime.date.today, input_formats=[
                           '%d-%m-%Y', '%Y-%m-%d', '%d.%m.%Y', '%Y.%m.%d'], )
    purpose = forms.CharField(label='Reason', required=True, widget=forms.Textarea(
        attrs={'name': 'body', 'rows': '3', 'cols': '50'}))

    patient = forms.ModelChoiceField(
        required=True, queryset=Pacient.objects.all(),
    )


class EditHospitalizationForm(forms.ModelForm):

    class Meta:
        model = Hospitalization
        fields = ('purpose', 'date')

    date = forms.DateField(required=True, initial=datetime.date.today, input_formats=[
                           '%d-%m-%Y', '%Y-%m-%d', '%d.%m.%Y', '%Y.%m.%d'], )
    purpose = forms.CharField(label='Reason', required=True, widget=forms.Textarea(
        attrs={'name': 'body', 'rows': '3', 'cols': '50'}))


class AddDoseForm(forms.ModelForm):

    class Meta:
        model = Dose
        fields = ('date', 'patient', 'medicine', 'application_method')

    date = forms.DateField(required=True, initial=datetime.date.today, input_formats=[
                           '%d-%m-%Y', '%Y-%m-%d', '%d.%m.%Y', '%Y.%m.%d'], )

    medicine = forms.ModelChoiceField(
        required=True, queryset=Medicine.objects.all())

    patient = forms.ModelChoiceField(
        required=True, queryset=Pacient.objects.all(),
    )

hospital/hospitalapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .forms import AddExaminationForm, EditExaminationForm, AddHospitalizationForm, EditHospitalizationForm, AddDoseForm

from .models import Department, Hospitalization, Examination, Medicine, Dose
from accounts.models import Doctor, Pacient


@login_required
def index(request):
    if request.user.is_pacient:
        hospitalizations = Hospitalization.objects.filter(
            pacient__user=request.user)
        examinations = Examination.objects.filter(pacient__user=request.user)
        dosages = Dose.objects.filter(pacient__user=request.user)
        return render(request, 'hospitalapp/index_pacient.html', context={'hospitalizations': hospitalizations,
                                                                          'examinations': examinations,
                                                                          'doses': dosages})

    elif request.user.is_doctor:
        return render(request, 'hospitalapp/index_doctor.html', context={'user': request.user})

    return render(request, 'hospitalapp/index.html', context={})


@login_required
def search_result(request):
    if request.method == 'POST':
        searched = request.POST.get('searched')

        if request.user.is_pacient:
            if not searched:
                qs = Doctor.objects.all()
            else:
                qs = Doctor.objects.filter(Q(user__first_name__iexact=searched) | Q(
                    user__last_name__iexact=searched) | Q(user__username__iexact=searched))
            return render(request, 'hospitalapp/search_result_doctors.html', {'searched': searched, 'qs': qs, 'search_doctors': True})

        elif request.user.is_doctor:
            if not searched:
                qs = Doctor.objects.all()
            else:
                qs = Pacient.objects.filter(Q(user__first_name__iexact=searched) | Q(
                    user__last_name__iexact=searched) | Q(user__username__iexact=searched))
            return render(request, 'hospitalapp/search_result_pacients.html', {'searched': searched, 'qs': qs})

    else:
        return render(request, 'hospitalapp/search_result.html')


@login_required
def patients(request):
    patients = Pacient.objects.all()
    return render(request, 'hospitalapp/patients.html', context={'patients': patients})


def doctors(request):
    qs = Doctor.objects.all()
    return render(request, 'hospitalapp/search_result_doctors.html', context={'qs': qs})


@login_required
def patient_details(request, patient_id):
    patient = get_object_or_404(Pacient, pk=patient_id)

    hospitalizations = Hospitalization.objects.filter(pacient=patient)
    examinations = Examination.objects.filter(pacient=patient)
    dosages = Dose.objects.filter(pacient=patient)
    return render(request, 'hospitalapp/patient_details.html', context={'patient': patient,
                                                                        'hospitalizations': hospitalizations,
                                                                        'examinations': examinations,
                                                                        'dosages': dosages})


@login_required
def examinations(request):
    examinations = Examination.objects.all()
    return render(request, 'hospitalapp/records/examinations.html', context={'examinations': examinations})


@login_required
def add_examination(request):
    if request.method == 'POST':
        form = AddExaminationForm(request.POST)
        if form.is_valid():
            examination = form.save(commit=False)
            examination.doctor = request.user.doctor
            examination.pacient = form.cleaned_data['patient']
            examination.save()

            return redirect('/examinations')
    else:
        form = AddExaminationForm

    return render(request, 'hospitalapp/records/add_examination.html', {'form': form})


@login_required
def edit_examination(request, examination_id):
    e = get_object_or_404(Examination, pk=examination_id)
    if request.method == 'POST':
        form = EditExaminationForm(request.POST, instance=e)
        if form.is_valid():
            e = form.save(commit=False)
            e.save()
            return redirect('/examinations')
    else:
        form = EditExaminationForm(instance=e)

    return render(request, 'hospitalapp/records/edit_examination.html', {'examination': e, 'form': form})


@login_required
def delete_examination(request, examination_id):
    e = get_object_or_404(Examination, pk=examination_id)
    if request.method == 'POST':
        e.delete()
        return redirect('/examinations')

    return render(request, 'hospitalapp/records/delete_examination.html', {'examination': e})


@login_required
def hospitalizations(request):
    hospitalizations = Hospitalization.objects.all()
    return render(request, 'hospitalapp/records/hospitalizations.html', context={'hospitalizations': hospitalizations})


@login_required
def add_hospitalization(request):
    if request.method == 'POST':
        form = AddHospitalizationForm(request.POST)
        if form.is_valid():
            hospitalization = form.save(commit=False)
            hospitalization.doctor = request.user.doctor
            hospitalization.pacient = form.cleaned_data['patient']
            hospitalization.save()

            return redirect('/hospitalizations')
    else:
        form = AddHospitalizationForm

    return render(request, 'hospitalapp/records/add_hospitalization.html', {'form': form})


@login_required
def edit_hospitalization(request, hospitalization_id):
    h = get_object_or_404(Hospitalization, pk=hospitalization_id)
    if request.method == 'POST':
        form = EditHospitalizationForm(request.POST, instance=h)
        if form.is_valid():
            h = form.save(commit=False)
            h.save()
            return redirect('/hospitalizations')
    else:
        form = EditHospitalizationForm(instance=h)

    return render(request, 'hospitalapp/records/edit_hospitalization.html', {'hospitalization': h, 'form': form})


@login_required
def delete_hospitalization(request, hospitalization_id):
    h = get_object_or_404(Hospitalization, pk=hospitalization_id)
    if request.method == 'POST':
        h.delete()
        return redirect('/hospitalizations')

    return render(request, 'hospitalapp/records/delete_hospitalization.html', {'hospitalization': h})


@login_required
def dosages(request):
    dosages = Dose.objects.all()
    return render(request, 'hospitalapp/records/dosages.html', context={'dosages': dosages})


@login_required
def add_dosage(request):
    if request.method == 'POST':
        form = AddDoseForm(request.POST)
        if form.is_valid():
            dosage = form.save(commit=False)
            dosage.pacient = form.cleaned_data['patient']
            dosage.save()

            return redirect('/dosages')
    else:
        form = AddDoseForm

    return render(request, 'hospitalapp/records/add_dosage.html', {'form': form})


@login_required
def delete_dosage(request, dosage_id):
    dosage = get_object_or_404(Dose, pk=dosage_id)
    if request.method == 'POST':
        dosage.delete()
        return redirect('/dosages')

    return render(request, 'hospitalapp/records/delete_dosage.html', {'dosage': dosage})


@login_required
def medications(request):
    medications = Medicine.objects.all()
    return render(request, 'hospitalapp/records/medications.html', context={'medications': medications})

hospital/hospitalapp/templates/hospitalapp/records/add_dosage.html
{% extends 'base.html' %}
{% block title %} Add dosage {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Add dosage record</h1>
	<p></p>
</div>

<div class="section">
    <form action="{% url 'add_dosage' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
</div>

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/add_examination.html
{% extends 'base.html' %}
{% block title %} Add examination {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Add examination record</h1>
	<p></p>
</div>

<div class="section">
    <form action="{% url 'add_examination' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
</div>

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/add_hospitalization.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Add examination record</h1>
	<p></p>
</div>

<div class="section">
    <form action="{% url 'add_hospitalization' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
</div>

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/delete_dosage.html
{% extends 'base.html' %}
{% block title %} Delete dosage {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Delete dosage record</h1>
	<p></p>
</div>

<div class="section">
    <form action="{% url 'delete_dosage' dosage.pk %}" method="POST">
        {% csrf_token %}
        Are you want to delete this record ?
        <input type="submit" value="Delete"/>
        <div>
            <button><a href="{{ request.META.HTTP_REFERER }}"> Cancel </a></button>
        </div>
    </form>
</div>

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/delete_examination.html
{% extends 'base.html' %}
{% block title %} Delete examination {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Delete examination record</h1>
	<p></p>
</div>

<div class="section">
    <form action="{% url 'delete_examination' examination.pk %}" method="POST">
        {% csrf_token %}
        Are you want to delete this record ?
        <input type="submit" value="Delete"/>
        <div>
            <button><a href="{{ request.META.HTTP_REFERER }}"> Cancel </a></button>
        </div>
    </form>
</div>

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/delete_hospitalization.html
{% extends 'base.html' %}
{% block title %} Delete hospitalization {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Delete hospitalization record</h1>
	<p></p>
</div>

<div class="section">
    <form action="{% url 'delete_hospitalization' hospitalization.pk %}" method="POST">
        {% csrf_token %}
        Are you want to delete this record ?
        <input type="submit" value="Delete"/>
        <div>
            <button><a href="{{ request.META.HTTP_REFERER }}"> Cancel </a></button>
        </div>
    </form>
</div>

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/dosages.html
{% extends 'base.html' %}
{% block title %} Dosages {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Dosage records</h1>
	<p></p>
</div>

<div class="section">
    <button><a href="{% url 'add_dosage' %}">Add dosage</a></button>
	<div class="preview">
		<h5><a style="text-decoration: underline;" href="{% url 'medications' %}">List of used medications</a></h5>
	</div>
</div>
{% for dosage in dosages %}
	<div class="section">
		<div class="preview">
			<div>
				<h4><i>{{ dosage.date }}</i></h4>
                <h5>Patient: </h5>
					<p>
						{{ dosage.pacient.user.first_name }} {{ dosage.pacient.user.last_name }}
						<a href="{% url 'patient_details' dosage.pacient.pk %}">({{ dosage.pacient }}</a>)
					</p>
                <h5>Medicine: </h5><p>{{ dosage.medicine }}</p>
                <h5>Application method: </h5><p>{{ dosage.get_application_method_display }}</p>
				<button><a href="{% url 'delete_dosage' dosage.pk %}">Delete</a></button>
			</div>
		</div>
	</div>
{% endfor %}

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/edit_examination.html
{% extends 'base.html' %}
{% block title %} Edit examination  {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Edit examination record</h1>
	<p></p>
</div>

<div class="section">
    <form action="{% url 'edit_examination' examination.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit">
    </form>
</div>

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/edit_hospitalization.html
{% extends 'base.html' %}
{% block title %} Edit hospitalization {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Edit hospitalization record</h1>
	<p></p>
</div>

<div class="section">
    <form action="{% url 'edit_hospitalization' hospitalization.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit">
    </form>
</div>

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/examinations.html
{% extends 'base.html' %}
{% block title %} Examinations {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Examination records</h1>
	<p></p>
</div>

<div class="section">
    <button><a href="{% url 'add_examination' %}">Add examination</a></button>
</div>
{% for exam in examinations %}
	<div class="section">
		<div class="preview">
			<div>
				<h4><i>{{ exam.date }}</i></h4>
                <h5>Patient: </h5>
					<p>
						{{ exam.pacient.user.first_name }} {{ exam.pacient.user.last_name }}
						<a href="{% url 'patient_details' exam.pacient.pk %}">({{ exam.pacient }}</a>)
					</p>
                <h5>Conducted by doctor: </h5>
					<p>{{ exam.doctor.user.first_name }} {{ exam.doctor.user.last_name }}({{ exam.doctor }})</p>
                <h5>Department: </h5><p>{{ exam.department }}</p>
                <h5>Result of examination: </h5><p>{{ exam.result }}</p>
				<button><a href="{% url 'edit_examination' exam.pk %}">Edit</a></button>
				<button><a href="{% url 'delete_examination' exam.pk %}">Delete</a></button>
			</div>
		</div>
	</div>
{% endfor %}

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/hospitalizations.html
{% extends 'base.html' %}
{% block title %} Hospitalizations {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>Hospitalization records</h1>
	<p></p>
</div>

<div class="section">
    <button><a href="{% url 'add_hospitalization' %}">Add hospitalization</a></button>
</div>
{% for hosp in hospitalizations %}
	<div class="section">
		<div class="preview">
			<div>
				<h4><i>{{ hosp.date }}</i></h4>
                <h5>Patient: </h5>
					<p>
						{{ hosp.pacient.user.first_name }} {{ hosp.pacient.user.last_name }}
						<a href="{% url 'patient_details' hosp.pacient.pk %}">({{ hosp.pacient }}</a>)
					</p>
                <h5>Admitted by doctor: </h5>
					<p>{{ hosp.doctor.user.first_name }} {{ hosp.doctor.user.last_name }}({{ hosp.doctor }})</p>
                <h5>Reason of hospitalization: </h5><p>{{ hosp.purpose }}</p>
				<button><a href="{% url 'edit_hospitalization' hosp.pk %}">Edit</a></button>
				<button><a href="{% url 'delete_hospitalization' hosp.pk %}">Delete</a></button>

			</div>
		</div>
	</div>
{% endfor %}

{% endblock %}

hospital/hospitalapp/templates/hospitalapp/records/medications.html
{% extends 'base.html' %}
{% block title %} Medications {% endblock %}

{% block content %}
<div id="pageheader">
	<h1>List of used medications</h1>
	<p></p>
</div>

{% for medication in medications %}
	<div class="section">
		<div class="preview">
			<div>
                <p>Title: <strong>{{ medication.title }}</strong></p>
                <p>Active substance: <i>{{ medication.active_substance }}</i></p>
                <p>Medication strenght: <i>{{ medication.medicine_strenght }}mg</i></p>
                <p>Contraindications/side effects: <i>{{ medication.contraindications }}</i></p>
			</div>
		</div>
	</div>
{% endfor %}

{% endblock %}